### ISSUE TITLE
Set and Measure clock speed

### ISSUE THREAD

**Issue by dougli1sqrd** [rustbox/esp32c3-vgaterm#3]
Currently I do not know exactly how to set the clock or clock speed on the esp32-c3. Similarly, it would be nice to measure, in software, the current speed of the core clock.

Apparently the esp32-c3 does not implement the RISC-V CSR `mcycle`, which counts the number of clock cycles that have passed. So there may be another esp32 specific mechanism for taking this kind of measurement?

**Comment by sethp** [comment]
I'm pretty sure you figured this out already, right? https://github.com/rustbox/esp32c3-vgaterm/blob/4184e69004751314a15284a9d3831ade11e8355d/src/bin/vgaterm.rs#L165-L194

Feel free to re-open if there's more work to do here!
